name: fightclub
description: Beat the enemy
publish_to: 'none'
version: 1.4.0+23
environment:
  sdk: ^3.11.0
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.1
  in_app_review: ^2.0.11
  shared_preferences: ^2.5.4

dev_dependencies:
  carapacik_lints: ^3.11.0
  #flutter_launcher_icons: ^0.14.4
  #flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - google_fonts/

flutter_launcher_icons:
  image_path: "assets/app/ic_logo.png"
  android: true
  adaptive_icon_background: "assets/app/ic_background.png"
  adaptive_icon_foreground: "assets/app/ic_foreground.png"
  min_sdk_android: 24
  ios: true
  remove_alpha_ios: true
  macos:
    generate: true
  windows:
    generate: true

flutter_native_splash:
  color: "#D5DEF0"
  image: "assets/app/ic_foreground.png"
  android: true
  ios: true
  web: true
